Update action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,11 +8,11 @@ runs:
   using: "composite"
   steps:
     - run: |
-      # fail if any commands fails
-      set -ex
+        # fail if any commands fails
+        set -ex
 
-      git fetch --prune --unshallow --tags
+        git fetch --prune --unshallow --tags
+
+        GIT_RELEASE_VERSION=$(git describe --tags --always --abbrev=0)
+        echo "RELEASE_VERSION=$GIT_RELEASE_VERSION" >> $GITHUB_ENV
       shell: bash
-
-      GIT_RELEASE_VERSION=$(git describe --tags --always --abbrev=0)
-      echo "RELEASE_VERSION=$GIT_RELEASE_VERSION" >> $GITHUB_ENV
